<?php

namespace App\Http\Controllers;

use App\Helpers\helper;
use Illuminate\Support\Facades\Mail;
use App\Models\Notification;
use App\Models\Setting;
use App\Models\Booking;
use App\Models\User;
use App\Models\Payout;
use App\Models\Category;
use App\Models\City;
use App\Models\Help;
use App\Models\PaymentMethods;
use App\Models\Bank;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Str;
use Illuminate\Support\Facades\Http;

class EmailSendController extends Controller
{

    public static function emailVerification($email, $otp, $username)
    {
        //return $email.' '.$otp;
        $getlogo = Setting::select('logo')->where('id', 1)->first();
        $logo = asset('storage/app/public/images/' . $getlogo->logo);

        $apiKey = env('MAILJET_APIKEY_PUBLIC');
        $apiSecret = env('MAILJET_APIKEY_PRIVATE');
        $senderEmail = env('SENDER_EMAIL');
        $senderName = env('SENDER_NAME');

        $recipientEmail = $email;
        $subject = 'Email verification';
        //$messageText = 'Email Verification OTP '.$otp;
        $messageText = '
        <!DOCTYPE html>

        <html>

            <head>

                <title>Email Verification</title>

            </head>

            <body>

                <div>
                    <div style="background:#ffffff;padding:15px">

                        <center>

                        <div style="width:100%;max-width:500px;background:#ffffff;height:180px">

                            <br>

                            <center>

                                <a href="#">

                                    <img alt="" src="' . $logo . '" width="100" height="100" style="display:block;font-family:Helvetica,Arial,sans-serif;color:#666666;font-size:16px" border="0" class="CToWUd">

                                </a>

                            </center>

                        </div>

                        <br>

                        <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:10px 0 10px 0">

                            <hr style="border:dashed 1px #e1e1e1;max-width:100%">

                            <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:0px 0 0px 0">

                                <div style="font-family:Lato,Helvetica,Arial,sans-serif;display:inline-block;margin:0px 0px 0 0;max-width:100%;width:100%;margin-right:0px">

                                    <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:20px 0 0px 0">

                                    <div bgcolor="#f8f4e8" align="left" style="padding:0px 0% 0px 0%;font-size:22px;line-height:25px;font-family:Lato,Helvetica,Arial,sans-serif;color:#19c0c2;font-weight:700" class="m_-7788511936867687679padding-copy">Dear ' . $username . ',</div>

                                    <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:15px 0 0px 0">

                                        <div bgcolor="#f8f4e8" align="left"style="padding:0px 0% 0px 0%;font-size:16px;line-height:25px;font-family:Lato,Helvetica,Arial,sans-serif;color:#6c6e6e;font-weight:500" class="m_-7788511936867687679padding-copy">

                                            Your Email Verification Code is<b style="color: #fe724c;"> '.$otp.' </b><br>Kindly verify your email to access your account.

                                        </div>

                                        <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:0px 0 10px 0">

                                            <hr style="border:dashed 1px #e1e1e1;max-width:100%">

                                        </div>

                                        <div style="display:inline-block;text-align:center;color:#777777;margin:0px auto 26px auto;font-family:Lato,Helvetica,Arial,sans-serif" align="center">

                                            <div style="font-size:12px;color:#777777;margin:12px auto 30px auto;font-family:Lato,Helvetica,Arial,sans-serif">

                                                <p style="font-size: 11px"><b>Note</b>:- Do not reply to this notification message,this message was auto-generated by the sender'."'s".' security system</p>

                                                <p style="line-height:1;font-size:12px;margin:0 20px 30px 20px;padding:0 0 0 0;color:#777777;font-family:Lato,Helvetica,Arial,sans-serif">

                                                All Rights Reserved.

                                                </p>

                                            </div>

                                        </div>

                                    </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                        </center>

                    </div>
                </div>

            </body>
      
        </html>';

        //echo $messageText;
        //die;

        $url = 'https://api.mailjet.com/v3.1/send';

        $data = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $senderEmail,
                        'Name' => $senderName,
                    ],
                    'To' => [
                        [
                            'Email' => $recipientEmail,
                        ],
                    ],
                    'Subject' => $subject,
                    //'TextPart' => 'Your plain text content goes here (e.g., Email Verification Code: ' . $otp . ')',
                    'HTMLPart' => $messageText,  // This is your HTML content
                ],
            ],
        ];

        $jsonData = json_encode($data);

        $ch = curl_init($url);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);

        // Set up basic authentication
        curl_setopt($ch, CURLOPT_USERPWD, "$apiKey:$apiSecret");

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if ($httpCode == 200) {
            return 1;
        } else {
            //return "Error: " . $response;
            return 0;
        }
    }
    
    public static function forgotpassword($email,$name,$password) {
        $getlogo = Setting::select('logo')->where('id', 1)->first();
        $logo = asset('storage/app/public/images/' . $getlogo->logo); 
        
        $apiKey = env('MAILJET_APIKEY_PUBLIC');
        $apiSecret = env('MAILJET_APIKEY_PRIVATE');
        $senderEmail = env('SENDER_EMAIL');
        $senderName = env('SENDER_NAME');

        $recipientEmail = $email;
        $subject = 'Reset Password';
        //$messageText = 'Email Verification OTP '.$otp;
        $messageText = '
        <!DOCTYPE html>

        <html>

            <head>

                <title>Reset Password</title>

            </head>

            <body>

                <div>
                    <div style="background:#ffffff;padding:15px">

                        <center>

                        <div style="width:100%;max-width:500px;background:#ffffff;height:180px">

                            <br>

                            <center>

                                <a href="#">

                                    <img alt="" src="' . $logo . '" width="100" height="100" style="display:block;font-family:Helvetica,Arial,sans-serif;color:#666666;font-size:16px" border="0" class="CToWUd">

                                </a>

                            </center>

                        </div>

                        <br>

                        <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:10px 0 10px 0">

                            <hr style="border:dashed 1px #e1e1e1;max-width:100%">

                            <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:0px 0 0px 0">

                                <div style="font-family:Lato,Helvetica,Arial,sans-serif;display:inline-block;margin:0px 0px 0 0;max-width:100%;width:100%;margin-right:0px">

                                    <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:20px 0 0px 0">

                                    <div bgcolor="#f8f4e8" align="left" style="padding:0px 0% 0px 0%;font-size:22px;line-height:25px;font-family:Lato,Helvetica,Arial,sans-serif;color:#19c0c2;font-weight:700" class="m_-7788511936867687679padding-copy">Dear ' . $name . ',</div>

                                    <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:15px 0 0px 0">

                                        <div bgcolor="#f8f4e8" align="left"style="padding:0px 0% 0px 0%;font-size:16px;line-height:25px;font-family:Lato,Helvetica,Arial,sans-serif;color:#6c6e6e;font-weight:500" class="m_-7788511936867687679padding-copy">
                                            Somebody (hopefully you) requested a new password for the account for '.$email.' <br>Your new password is<b style="color: #fe724c;"> '.$password.'</b><br>Kindly update your password after login. We will be here to help you with any step along the way
                                            
                                        </div>

                                        <div style="width:100%;max-width:580px;background:#ffffff;height:auto;padding:0px 0 10px 0">

                                            <hr style="border:dashed 1px #e1e1e1;max-width:100%">

                                        </div>

                                        <div style="display:inline-block;text-align:center;color:#777777;margin:0px auto 26px auto;font-family:Lato,Helvetica,Arial,sans-serif" align="center">

                                            <div style="font-size:12px;color:#777777;margin:12px auto 30px auto;font-family:Lato,Helvetica,Arial,sans-serif">

                                                <p style="font-size: 11px"><b>Note</b>:- Do not reply to this notification message,this message was auto-generated by the sender'."'s".' security system</p>

                                                <p style="line-height:1;font-size:12px;margin:0 20px 30px 20px;padding:0 0 0 0;color:#777777;font-family:Lato,Helvetica,Arial,sans-serif">

                                                All Rights Reserved.

                                                </p>

                                            </div>

                                        </div>

                                    </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                        </center>

                    </div>
                </div>

            </body>
      
        </html>';

        //echo $messageText;
        //die;

        $url = 'https://api.mailjet.com/v3.1/send';

        $data = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $senderEmail,
                        'Name' => $senderName,
                    ],
                    'To' => [
                        [
                            'Email' => $recipientEmail,
                        ],
                    ],
                    'Subject' => $subject,
                    //'TextPart' => 'Your plain text content goes here (e.g., Email Verification Code: ' . $otp . ')',
                    'HTMLPart' => $messageText,  // This is your HTML content
                ],
            ],
        ];

        $jsonData = json_encode($data);

        $ch = curl_init($url);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);

        // Set up basic authentication
        curl_setopt($ch, CURLOPT_USERPWD, "$apiKey:$apiSecret");

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if ($httpCode == 200) {
            return 1;
        } else {
            return "Error: " . $response;
            //return 0;
        }
    }
    
    //done
    public static function create_booking($bid)
    {
        $getlogo = Setting::select('logo')->where('id', '=', '1')->first();
        $bookingdata = Booking::where('booking_id',$bid)->first();
        $userdata = User::where('id',$bookingdata->user_id)->first();
        $title = trans('messages.place_booking');
        $app_name = trans('labels.app_name');
        $logo = asset('storage/app/public/images/'.$getlogo->logo);
        $email = $userdata->email;
        $name = $userdata->name;
        $bid = $bookingdata->booking_id;

        
        $apiKey = env('MAILJET_APIKEY_PUBLIC');
        $apiSecret = env('MAILJET_APIKEY_PRIVATE');
        $senderEmail = env('SENDER_EMAIL');
        $senderName = env('SENDER_NAME');

        $recipientEmail = $email;
        $subject = $title;
        //$messageText = 'Email Verification OTP '.$otp;
        $messageText = '
            <!DOCTYPE html>
            <html>
            
            <head>
                <title></title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <style type="text/css">
                    
                    body {
                        height: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        width: 100% !important;
                    }
                    body,table,td,a {-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;}
                    table,td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
                    table {border-collapse: collapse !important;}
                    img {-ms-interpolation-mode: bicubic;}
                    img {border: 0;
                        height: auto;
                        line-height: 100%;
                        outline: none;
                        text-decoration: none;
                    }
            
                    a[x-apple-data-detectors] {
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }
                    div[style*="margin: 16px 0;"] {margin: 0 !important;}
                    @media screen and (max-width: 480px) {
                        .mobile-hide {display: none !important;}
                        .mobile-center {text-align: center !important;}
                    }
                </style>
            
            <body style="margin: 0 !important; padding: 0 !important; background-color: #eeeeee;" bgcolor="#eeeeee">
            
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td align="center" style="background-color: #eeeeee;" bgcolor="#eeeeee">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                <tr>
                                    <td align="center" style="padding: 35px 35px 20px 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 25px;"> <img src="https://img.icons8.com/carbon-copy/100/000000/checked-checkbox.png" width="125" height="120" style="display: block; border: 0px;" /><br>
                                                    <h2 style="font-size: 30px; font-weight: 800; line-height: 36px; color: #333333; margin: 0;"> Thank You For Your Booking! </h2>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Hey '. $name .',</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Thank you for your booking .</p>
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Your booking has been placed with Booking ID :  <span style="font-size: 12px; font-weight: 800; line-height: 24px; color: #777777;">'.$bid.'</span> and it will be processed as soon as possible by the admin.</p>
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">To track booking status : Log-in to your account > select Bookings from Menu > Search booking with id <span style="font-size: 12px; font-weight: 800; line-height: 24px; color: #777777;">'.$bid.' </span> > Click on Booking .
                                                    </p>
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">You will get an booking confirmation email from admin soon .
                                                    </p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" style="padding: 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                                            <tr>
                                                <td align="center">
                                                    <img src="'.$logo.'" width="37" height="37" style="display: block; border: 0px;" />
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
                                                    <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">'.$app_name.'</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
                                                    <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #777777;"> If you did not booked a service OR you are not registered using this email address, please ignore this email</a>.</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </body>
            
            </html>
        ';

        //echo $messageText;
        //die;

        $url = 'https://api.mailjet.com/v3.1/send';

        $data = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $senderEmail,
                        'Name' => $senderName,
                    ],
                    'To' => [
                        [
                            'Email' => $recipientEmail,
                        ],
                    ],
                    'Subject' => $subject,
                    //'TextPart' => 'Your plain text content goes here (e.g., Email Verification Code: ' . $otp . ')',
                    'HTMLPart' => $messageText,  // This is your HTML content
                ],
            ],
        ];

        $jsonData = json_encode($data);

        $ch = curl_init($url);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);

        // Set up basic authentication
        curl_setopt($ch, CURLOPT_USERPWD, "$apiKey:$apiSecret");

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if ($httpCode == 200) {
            return 1;
        } else {
            return "Error: " . $response;
            //return 0;
        }
    }
    
     //$helper = helper::accept_booking
    public static function accept_booking($bid)
    {
        $getlogo = Setting::select('logo')->where('id', '=', '1')->first();
        $bookingdata = Booking::where('id',$bid)->first();
        $userdata = User::where('id',$bookingdata->user_id)->first();
        $title = trans('messages.accept_booking');
        $app_name = trans('labels.app_name');
        $logo = asset('storage/app/public/images/'.$getlogo->logo);
        $date = $bookingdata->date;
        $email = $userdata->email;
        $name = $userdata->name;
        $bid = $bookingdata->booking_id;
        
        $apiKey = env('MAILJET_APIKEY_PUBLIC');
        $apiSecret = env('MAILJET_APIKEY_PRIVATE');
        $senderEmail = env('SENDER_EMAIL');
        $senderName = env('SENDER_NAME');

        $recipientEmail = $email;
        $subject = $title;
        //$messageText = 'Email Verification OTP '.$otp;
        $messageText = '
        <!DOCTYPE html>
            <html>
            
            <head>
                <title></title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <style type="text/css">
                    
                    body {
                        height: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        width: 100% !important;
                    }
                    body,table,td,a {-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;}
                    table,td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
                    table {border-collapse: collapse !important;}
                    img {-ms-interpolation-mode: bicubic;}
                    img {border: 0;
                        height: auto;
                        line-height: 100%;
                        outline: none;
                        text-decoration: none;
                    }
            
                    a[x-apple-data-detectors] {
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }
            		div[style*="margin: 16px 0;"] {margin: 0 !important;}
                    @media screen and (max-width: 480px) {
                        .mobile-hide {display: none !important;}
                        .mobile-center {text-align: center !important;}
                    }
                </style>
            
            <body style="margin: 0 !important; padding: 0 !important; background-color: #eeeeee;" bgcolor="#eeeeee">
            
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td align="center" style="background-color: #eeeeee;" bgcolor="#eeeeee">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                <tr>
                                    <td align="center" style="padding: 35px 35px 20px 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 25px;"> <img src="https://img.icons8.com/carbon-copy/100/000000/checked-checkbox.png" width="125" height="120" style="display: block; border: 0px;" /><br>
                                                    <h2 style="font-size: 30px; font-weight: 800; line-height: 36px; color: #333333; margin: 0;"> Thank You For Your Booking! </h2>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Hey '.$name.', </p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Your Booking has been accepted By Studio .</p>
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Your Booking id is :
                                                     	<span style="font-size: 16px; font-weight: 800; line-height: 24px; color: #777777;">'.$bid.'</span>
                                                 	</p>
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Your Booking will be done By Studio on your booking date 
                                                    	<span style="font-size: 16px; font-weight: 800; line-height: 24px; color: #777777;"> '.$date.' </span>.
                                                    </p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" style="padding: 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                                            <tr>
                                                <td align="center">
                                                	<img src="'.$logo.'" width="37" height="37" style="display: block; border: 0px;" />
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
                                                    <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">'.$app_name.'</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
                                                    <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #777777;"> If you did not booked a service OR you are not registered using this email address, please ignore this email</a>.</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </body>
            
            </html>
        ';

        //echo $messageText;
        //die;

        $url = 'https://api.mailjet.com/v3.1/send';

        $data = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $senderEmail,
                        'Name' => $senderName,
                    ],
                    'To' => [
                        [
                            'Email' => $recipientEmail,
                        ],
                    ],
                    'Subject' => $subject,
                    //'TextPart' => 'Your plain text content goes here (e.g., Email Verification Code: ' . $otp . ')',
                    'HTMLPart' => $messageText,  // This is your HTML content
                ],
            ],
        ];

        $jsonData = json_encode($data);

        $ch = curl_init($url);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);

        // Set up basic authentication
        curl_setopt($ch, CURLOPT_USERPWD, "$apiKey:$apiSecret");

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if ($httpCode == 200) {
            return 1;
        } else {
            return "Error: " . $response;
            //return 0;
        }
        
    }
    
    //$helper = helper::assign_handyman
    public static function assign_handyman($bid)
    {
        $getlogo = Setting::select('logo')->where('id', '=', '1')->first();
        $bookingdata = Booking::where('id',$bid)->first();
        $userdata = User::where('id',$bookingdata->user_id)->first();
        $handymandata = User::where('id',$bookingdata->handyman_id)->first();
        $title = trans('messages.assign_handyman');
        $app_name = trans('labels.app_name');
        $logo = asset('storage/app/public/images/'.$getlogo->logo);
        $date = $bookingdata->date;
        $email = $userdata->email;
        $name = $userdata->name;
        $handyman_name = $handymandata->name;
        $handyman_email = $handymandata->email;
        $handyman_mobile = $handymandata->mobile;
        $bid = $bookingdata->booking_id;
        
        
        $apiKey = env('MAILJET_APIKEY_PUBLIC');
        $apiSecret = env('MAILJET_APIKEY_PRIVATE');
        $senderEmail = env('SENDER_EMAIL');
        $senderName = env('SENDER_NAME');

        $recipientEmail = $email;
        $subject = $title;
        //$messageText = 'Email Verification OTP '.$otp;
        $messageText = '
        <!DOCTYPE html>
            <html>
            
            <head>
                <title></title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <style type="text/css">
                    
                    body {
                        height: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        width: 100% !important;
                    }
                    body,table,td,a {-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;}
                    table,td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
                    table {border-collapse: collapse !important;}
                    img {-ms-interpolation-mode: bicubic;}
                    img {border: 0;
                        height: auto;
                        line-height: 100%;
                        outline: none;
                        text-decoration: none;
                    }
            
                    a[x-apple-data-detectors] {
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }
                    div[style*="margin: 16px 0;"] {margin: 0 !important;}
                    @media screen and (max-width: 480px) {
                        .mobile-hide {display: none !important;}
                        .mobile-center {text-align: center !important;}
                    }
                </style>
            
            <body style="margin: 0 !important; padding: 0 !important; background-color: #eeeeee;" bgcolor="#eeeeee">
            
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td align="center" style="background-color: #eeeeee;" bgcolor="#eeeeee">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                <tr>
                                    <td align="center" style="padding: 35px 35px 20px 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 25px;"> 
                                                    <img src="https://img.icons8.com/emoji/48/000000/check-mark-emoji.png" width="125" height="120" style="display: block; border: 0px;"/><br>
                                                    <h2 style="font-size: 30px; font-weight: 800; line-height: 36px; color: #333333; margin: 0;"> Photographer assigned to Booking!</h2>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Hey '.$name.',</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Photographer has been assigned to your booking by Studio .</p>
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Your Booking '.$bid.' will be done by Photographer on your booking date <span style="font-size: 16px; font-weight: 800; line-height: 24px; color: #777777;"> '.$date.' </span>. </p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="padding-top: 20px;">
                                                    <table cellspacing="0" cellpadding="0" border="0" width="100%">
                                                        <tr>
                                                            <td colspan="2" width="75%" align="left" bgcolor="#eeeeee" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 800; line-height: 24px; padding: 10px;"> Photographer Information </td>
                                                        </tr>
                                                        <tr>
                                                            <td width="25%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;"> Name</td>
                                                            <td width="75%" align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding: 15px 10px 5px 10px;"> '.$handyman_name.' </td>
                                                        </tr>
                                                       
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" style="padding: 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                                            <tr>
                                                <td align="center">
                                                    <img src="';$logo.'" width="37" height="37" style="display: block; border: 0px;" />
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
                                                    <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">'.$app_name.'</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
                                                    <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #777777;"> If you are not registered with us using this email address, please ignore this email</a>.</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </body>
            
            </html>
        ';

        //echo $messageText;
        //die;

        $url = 'https://api.mailjet.com/v3.1/send';

        $data = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $senderEmail,
                        'Name' => $senderName,
                    ],
                    'To' => [
                        [
                            'Email' => $recipientEmail,
                        ],
                    ],
                    'Subject' => $subject,
                    //'TextPart' => 'Your plain text content goes here (e.g., Email Verification Code: ' . $otp . ')',
                    'HTMLPart' => $messageText,  // This is your HTML content
                ],
            ],
        ];

        $jsonData = json_encode($data);

        $ch = curl_init($url);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);

        // Set up basic authentication
        curl_setopt($ch, CURLOPT_USERPWD, "$apiKey:$apiSecret");

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if ($httpCode == 200) {
            return 1;
        } else {
            return "Error: " . $response;
            //return 0;
        }
    }
    
    //$helper = helper::complete_booking
    public static function complete_booking($bid)
    {
        $getlogo = Setting::select('logo')->where('id', '=', '1')->first();
        $bookingdata = Booking::where('id',$bid)->first();
        $userdata = User::where('id',$bookingdata->user_id)->first();
        $title = trans('messages.complete_booking');
        $app_name = trans('labels.app_name');
        $logo = asset('storage/app/public/images/'.$getlogo->logo);
        $date = $bookingdata->date;
        $email = $userdata->email;
        $name = $userdata->name;
        $bid = $bookingdata->booking_id;
        
        $apiKey = env('MAILJET_APIKEY_PUBLIC');
        $apiSecret = env('MAILJET_APIKEY_PRIVATE');
        $senderEmail = env('SENDER_EMAIL');
        $senderName = env('SENDER_NAME');

        $recipientEmail = $email;
        $subject = $title;
        //$messageText = 'Email Verification OTP '.$otp;
        $messageText = '
        <!DOCTYPE html>
            <html>
            
            <head>
                <title></title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <style type="text/css">
                    
                    body {
                        height: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        width: 100% !important;
                    }
                    body,table,td,a {-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;}
                    table,td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
                    table {border-collapse: collapse !important;}
                    img {-ms-interpolation-mode: bicubic;}
                    img {border: 0;
                        height: auto;
                        line-height: 100%;
                        outline: none;
                        text-decoration: none;
                    }
            
                    a[x-apple-data-detectors] {
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }
                    div[style*="margin: 16px 0;"] {margin: 0 !important;}
                    @media screen and (max-width: 480px) {
                        .mobile-hide {display: none !important;}
                        .mobile-center {text-align: center !important;}
                    }
                </style>
            
            <body style="margin: 0 !important; padding: 0 !important; background-color: #eeeeee;" bgcolor="#eeeeee">
            
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td align="center" style="background-color: #eeeeee;" bgcolor="#eeeeee">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                <tr>
                                    <td align="center" style="padding: 35px 35px 20px 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 25px;"> 
                                                    <img src="https://img.icons8.com/emoji/48/000000/check-mark-emoji.png" width="125" height="120" style="display: block; border: 0px;"/><br>
                                                    <h2 style="font-size: 30px; font-weight: 800; line-height: 36px; color: #333333; margin: 0;"> Booking has been Completed!!</h2>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Hey '.$name.', </p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Your Booking has been completed By Admin .</p>
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Your Booking '.$bid.' has been completed By Admin . </p>
            
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" style="padding: 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                                            <tr>
                                                <td align="center">
                                                    <img src="'.$logo.'" width="37" height="37" style="display: block; border: 0px;" />
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
                                                    <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">'.$app_name.'</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
                                                    <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #777777;"> If you are not registered with us using this email address, please ignore this email</a>.</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </body>
            
            </html>
        ';

        //echo $messageText;
        //die;

        $url = 'https://api.mailjet.com/v3.1/send';

        $data = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $senderEmail,
                        'Name' => $senderName,
                    ],
                    'To' => [
                        [
                            'Email' => $recipientEmail,
                        ],
                    ],
                    'Subject' => $subject,
                    //'TextPart' => 'Your plain text content goes here (e.g., Email Verification Code: ' . $otp . ')',
                    'HTMLPart' => $messageText,  // This is your HTML content
                ],
            ],
        ];

        $jsonData = json_encode($data);

        $ch = curl_init($url);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);

        // Set up basic authentication
        curl_setopt($ch, CURLOPT_USERPWD, "$apiKey:$apiSecret");

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if ($httpCode == 200) {
            return 1;
        } else {
            return "Error: " . $response;
            //return 0;
        }
        
    }
    
    //done
    public static function cancel_booking($bid)
    {
        $getlogo = Setting::select('logo')->where('id', '=', '1')->first();
        $bookingdata = Booking::where('id',$bid)->first();
        $userdata = User::where('id',$bookingdata->user_id)->first();
        $title = trans('messages.cancel_booking');
        $app_name = trans('labels.app_name');
        $logo = asset('storage/app/public/images/'.$getlogo->logo);
        $date = $bookingdata->date;
        $email = $userdata->email;
        $name = $userdata->name;
        
        if($bookingdata->canceled_by == 1){
            $description = "Your Booking ".$bookingdata->booking_id." has been cancelled By Admin.";
        }else{
            $description = "Your Booking ".$bookingdata->booking_id." has been cancelled by You.";
        }
        
        $apiKey = env('MAILJET_APIKEY_PUBLIC');
        $apiSecret = env('MAILJET_APIKEY_PRIVATE');
        $senderEmail = env('SENDER_EMAIL');
        $senderName = env('SENDER_NAME');

        $recipientEmail = $email;
        $subject = $title;
        //$messageText = 'Email Verification OTP '.$otp;
        $messageText = '
        <!DOCTYPE html>
            <html>
            
            <head>
                <title></title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <style type="text/css">
                    
                    body {
                        height: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        width: 100% !important;
                    }
                    body,table,td,a {-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;}
                    table,td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
                    table {border-collapse: collapse !important;}
                    img {-ms-interpolation-mode: bicubic;}
                    img {border: 0;
                        height: auto;
                        line-height: 100%;
                        outline: none;
                        text-decoration: none;
                    }
            
                    a[x-apple-data-detectors] {
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }
                    div[style*="margin: 16px 0;"] {margin: 0 !important;}
                    @media screen and (max-width: 480px) {
                        .mobile-hide {display: none !important;}
                        .mobile-center {text-align: center !important;}
                    }
                </style>
            
            <body style="margin: 0 !important; padding: 0 !important; background-color: #eeeeee;" bgcolor="#eeeeee">
            
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <td align="center" style="background-color: #eeeeee;" bgcolor="#eeeeee">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                <tr>
                                    <td align="center" style="padding: 35px 35px 20px 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:660px;">
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 25px;"> 
                                                    <img src="https://img.icons8.com/cute-clipart/60/000000/multiply.png" width="125" height="120" style="display: block; border: 0px;" /><br>
                                                    <h2 style="font-size: 30px; font-weight: 800; line-height: 36px; color: #333333; margin: 0;"> Booking has been Cancelled!!</h2>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">Hey '.$name.', </p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 10px;">
            
                                                    <p style="font-size: 16px; font-weight: 400; line-height: 24px; color: #777777;">'.$description.'</p>
            
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" style="padding: 35px; background-color: #ffffff;" bgcolor="#ffffff">
                                        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                                            <tr>
                                                <td align="center">
                                                    <img src="'.$logo.'" width="37" height="37" style="display: block; border: 0px;" />
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px; padding: 5px 0 10px 0;">
                                                    <p style="font-size: 14px; font-weight: 800; line-height: 18px; color: #333333;">'.$app_name.'</p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="font-family: Open Sans, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; line-height: 24px;">
                                                    <p style="font-size: 14px; font-weight: 400; line-height: 20px; color: #777777;"> If you did not booked a service OR you are not registered with us using this email address, please ignore this email</a>.</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </body>
            
            </html>
        ';

        //echo $messageText;
        //die;

        $url = 'https://api.mailjet.com/v3.1/send';

        $data = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $senderEmail,
                        'Name' => $senderName,
                    ],
                    'To' => [
                        [
                            'Email' => $recipientEmail,
                        ],
                    ],
                    'Subject' => $subject,
                    //'TextPart' => 'Your plain text content goes here (e.g., Email Verification Code: ' . $otp . ')',
                    'HTMLPart' => $messageText,  // This is your HTML content
                ],
            ],
        ];

        $jsonData = json_encode($data);

        $ch = curl_init($url);

        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);

        // Set up basic authentication
        curl_setopt($ch, CURLOPT_USERPWD, "$apiKey:$apiSecret");

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if ($httpCode == 200) {
            return 1;
        } else {
            return "Error: " . $response;
            //return 0;
        }
        
        
        
    }
    
}
